backend:
  name: bitbucket
  branch: master
  repo: riyaadh-fakier/netlify-demo
  api_root: https://api.bitbucket.org/2.0
  base_url: https://api.netlify.com

collections:
  - name: "articles"
    label: "Articles"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: _posts/{{slug}}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "app"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["getting-started", "communication", "working-at-nml", "development", "front-end", "performance", "qa"]}
      - {label: "Snippet", name: "snippet", widget: "string"}
      - {Label: "Pin", name: "sticky", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

media_folder: "assets/images"
public_folder: "assets/images/uploads"